name: Save Email

on:
  repository_dispatch:
    types: [new_email]

jobs:
  save-email:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Save email
        run: node scripts/save-email.js "${{ github.event.client_payload.email }}"

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add emails.json
          git commit -m "add email" || exit 0
          git push